// src/lib/dummy-pos-data.ts
import { Category, Product, Partner, Order } from '@/types/pos';

export const DUMMY_CATEGORIES: Category[] = [
  { _id: 'cat-all', name: 'Semua Menu', slug: 'all' },
  { _id: 'cat-1', name: 'Makanan Utama', slug: 'makanan-utama' },
  { _id: 'cat-2', name: 'Lauk & Sambal', slug: 'lauk-sambal' },
  { _id: 'cat-3', name: 'Minuman Segar', slug: 'minuman-segar' },
  { _id: 'cat-4', name: 'Cemilan Tradisional', slug: 'cemilan-tradisional' },
];

export const DUMMY_PRODUCTS: Product[] = [
  {
    _id: 'prod-101',
    name: 'Ayam Bakar Kemiren',
    description: 'Ayam kampung bakar bumbu khas Kemiren Banyuwangi yang gurih dan meresap.',
    price: 35000,
    stock: 24,
    image: 'https://images.unsplash.com/photo-1598515214211-89d3c73ae83b?auto=format&fit=crop&w=600&q=80',
    categoryId: 'cat-1',
    category: { _id: 'cat-1', name: 'Makanan Utama' },
    isAvailable: true,
  },
  {
    _id: 'prod-102',
    name: 'Ayam Goreng Kampung',
    description: 'Ayam goreng renyah dengan serundeng laos gurih.',
    price: 32000,
    stock: 18,
    image: 'https://images.unsplash.com/photo-1626082927389-6cd097cdc6ec?auto=format&fit=crop&w=600&q=80',
    categoryId: 'cat-1',
    category: { _id: 'cat-1', name: 'Makanan Utama' },
    isAvailable: true,
  },
  {
    _id: 'prod-103',
    name: 'Gurame Asam Manis',
    description: 'Ikan gurame segar goreng krispi dengan saus asam manis buah nanas.',
    price: 65000,
    stock: 12,
    image: 'https://images.unsplash.com/photo-1534939561126-855b8675edd7?auto=format&fit=crop&w=600&q=80',
    categoryId: 'cat-1',
    category: { _id: 'cat-1', name: 'Makanan Utama' },
    isAvailable: true,
  },
  {
    _id: 'prod-104',
    name: 'Pecel Rawon Banyuwangi',
    description: 'Perpaduan unik kuah rawon hitam pekat dengan sayuran sambal pecel.',
    price: 28000,
    stock: 20,
    image: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=600&q=80',
    categoryId: 'cat-1',
    category: { _id: 'cat-1', name: 'Makanan Utama' },
    isAvailable: true,
  },
  {
    _id: 'prod-201',
    name: 'Sambal Tempong Dapoer Thatha',
    description: 'Sambal terasi segar super pedas lengkap dengan lalapan kemangi & timun.',
    price: 12000,
    stock: 40,
    image: 'https://images.unsplash.com/photo-1572449043416-55f4685c9bb7?auto=format&fit=crop&w=600&q=80',
    categoryId: 'cat-2',
    category: { _id: 'cat-2', name: 'Lauk & Sambal' },
    isAvailable: true,
  },
  {
    _id: 'prod-202',
    name: 'Tahu Tempe Goreng Kemul',
    description: 'Tahu dan tempe kedelai segar goreng renyah.',
    price: 15000,
    stock: 30,
    image: 'https://images.unsplash.com/photo-1626082929543-68bf79a55224?auto=format&fit=crop&w=600&q=80',
    categoryId: 'cat-2',
    category: { _id: 'cat-2', name: 'Lauk & Sambal' },
    isAvailable: true,
  },
  {
    _id: 'prod-301',
    name: 'Es Teh Manis Segar',
    description: 'Teh melati seduh dingin manis alami.',
    price: 7000,
    stock: 50,
    image: 'https://images.unsplash.com/photo-1556679343-c7306c1976bc?auto=format&fit=crop&w=600&q=80',
    categoryId: 'cat-3',
    category: { _id: 'cat-3', name: 'Minuman Segar' },
    isAvailable: true,
  },
  {
    _id: 'prod-302',
    name: 'Es Jeruk Peras Segar',
    description: 'Jeruk peras manis segar tanpa pemanis buatan.',
    price: 10000,
    stock: 45,
    image: 'https://images.unsplash.com/photo-1621506289937-a8e4df240d0b?auto=format&fit=crop&w=600&q=80',
    categoryId: 'cat-3',
    category: { _id: 'cat-3', name: 'Minuman Segar' },
    isAvailable: true,
  },
  {
    _id: 'prod-303',
    name: 'Kopi Osing Kemiren',
    description: 'Kopi robusta sangrai tradisional Desa Kemiren.',
    price: 12000,
    stock: 35,
    image: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&w=600&q=80',
    categoryId: 'cat-3',
    category: { _id: 'cat-3', name: 'Minuman Segar' },
    isAvailable: true,
  },
  {
    _id: 'prod-401',
    name: 'Pisang Goreng Keju Aren',
    description: 'Pisang kepok manis goreng dengan parutan keju dan siraman gula aren.',
    price: 18000,
    stock: 25,
    image: 'https://images.unsplash.com/photo-1528735602780-2552fd46c7af?auto=format&fit=crop&w=600&q=80',
    categoryId: 'cat-4',
    category: { _id: 'cat-4', name: 'Cemilan Tradisional' },
    isAvailable: true,
  },
];

export const DUMMY_PARTNERS: Partner[] = [
  { _id: 'part-1', name: 'Travel Jejak Kembara', isActive: true },
  { _id: 'part-2', name: 'Banyuwangi Tour Guide Club', isActive: true },
  { _id: 'part-3', name: 'Ijen Explorer Travel', isActive: true },
];

export const DUMMY_FAKTUR_GANTUNG: Order[] = [
  {
    _id: 'order-001',
    invoiceNumber: 'INV-20260803-001',
    tableNumber: '04',
    customerName: 'Pak Budi Santoso',
    orderType: 'dine_in',
    paymentStatus: 'unpaid',
    items: [
      { productId: 'prod-101', name: 'Ayam Bakar Kemiren', price: 35000, quantity: 2 },
      { productId: 'prod-201', name: 'Sambal Tempong Dapoer Thatha', price: 12000, quantity: 1 },
      { productId: 'prod-301', name: 'Es Teh Manis Segar', price: 7000, quantity: 2 },
    ],
    subtotal: 96000,
    dpAmount: 0,
    guideCommission: 0,
    grandTotal: 96000,
    createdAt: '03 Agu 2026 12:15',
    isSmartMerged: false,
  },
  {
    _id: 'order-002',
    invoiceNumber: 'INV-20260803-002',
    tableNumber: '07',
    customerName: 'Meja 07 (Pesan Mandiri QR)',
    orderType: 'qr_order',
    paymentStatus: 'unpaid',
    items: [
      { productId: 'prod-103', name: 'Gurame Asam Manis', price: 65000, quantity: 1, notes: 'Saus dipisah' },
      { productId: 'prod-102', name: 'Ayam Goreng Kampung', price: 32000, quantity: 2 },
      { productId: 'prod-202', name: 'Tahu Tempe Goreng Kemul', price: 15000, quantity: 1 },
      { productId: 'prod-302', name: 'Es Jeruk Peras Segar', price: 10000, quantity: 3 },
    ],
    subtotal: 174000,
    dpAmount: 0,
    guideCommission: 0,
    grandTotal: 174000,
    createdAt: '03 Agu 2026 12:40',
    isSmartMerged: true, // Hasil dari 2 kali order via Barcode QR yang otomatis digabungkan
  },
  {
    _id: 'order-003',
    invoiceNumber: 'INV-20260803-003',
    tableNumber: '12',
    customerName: 'Rombongan Keluarga Pak Handoko (Reservasi)',
    orderType: 'reservation',
    paymentStatus: 'dp_paid',
    items: [
      { productId: 'prod-101', name: 'Ayam Bakar Kemiren', price: 35000, quantity: 10 },
      { productId: 'prod-103', name: 'Gurame Asam Manis', price: 65000, quantity: 4 },
      { productId: 'prod-201', name: 'Sambal Tempong Dapoer Thatha', price: 12000, quantity: 5 },
      { productId: 'prod-302', name: 'Es Jeruk Peras Segar', price: 10000, quantity: 14 },
    ],
    subtotal: 810000,
    dpAmount: 400000, // DP 50% sudah dibayar saat booking
    guideCommission: 50000, // Komisi guide mitra travel
    grandTotal: 360000, // Sisa tagihan (810.000 - 400.000 - 50.000)
    partnerId: 'part-1',
    partnerName: 'Travel Jejak Kembara',
    createdAt: '03 Agu 2026 13:00',
    isSmartMerged: false,
  },
];
